### ISSUE TITLE
Unexpected token e in JSON at position 0

### ISSUE THREAD

**Issue by GoAwayGod** [iFraan/vandal.js#1]
receiving an Unexpected token e in JSON at position 0

![image](https://user-images.githubusercontent.com/78283377/167750384-845e0053-ff72-4cc3-a8e1-c1a8b6dbaff8.png)

**Comment by iFraan** [comment]
Looks like the site is blocking curl from accessing it. 
Can you try using the url in your browser? _(changing the username and tag)_
https://api.tracker.gg/api/v2/valorant/standard/profile/riot/{USERNAME}%23{TAG}
I've updated the user-agent to a more modern one so updating the module using **npm i vandal.js** maybe would fix it.

**Comment by GoAwayGod** [comment]
![image](https://user-images.githubusercontent.com/78283377/168187687-50d339ac-43f7-4251-aa03-95aeabde0941.png)
using link: https://api.tracker.gg/api/v2/valorant/standard/profile/riot/iFraan_%23G4G
when i access it from a browser, it works fine. i am able to see the JSON.
![image](https://user-images.githubusercontent.com/78283377/168188603-d0f851ed-6495-424b-927f-8255e791239e.png)
however when I use it in the bot, it returns this error

**Comment by iFraan** [comment]
try to open a terminal and use 
`curl --max-time 5 --user-agent 'Chrome/99' --url https://api.tracker.gg/api/v2/valorant/standard/profile/riot/iFraan%23G4G`
Or try updating curl with
https://curl.se/windows/dl-7.83.1/curl-7.83.1-win64-mingw.zip

**Comment by iFraan** [comment]
also, make sure you dont have a curl file (even if end with js) in your root folder, so it uses the one in the default path

**Comment by GoAwayGod** [comment]
running the 

> try to open a terminal and use `curl --max-time 5 --user-agent 'Chrome/99' --url https://api.tracker.gg/api/v2/valorant/standard/profile/riot/iFraan%23G4G` Or try updating curl with https://curl.se/windows/dl-7.83.1/curl-7.83.1-win64-mingw.zip

Running this returned error code: 1020

currently the version of curl im using is 7.79.1 (Windows) libcurl/7.79.1 Schannel

there is no exe to run in the curl file, also the readme is not clear on where to use this file

**Comment by iFraan** [comment]
Usage is simple, you install the package with ```npm i vandal.js``` and call the functions. Error 1020 means cloudfare is forbiding your connection. Closing this since i cant replicate in either of my 3 machines (win10, win11 and ubuntu).
