### ISSUE TITLE
Friendly Reminder: The API that you are using is not public

### ISSUE THREAD

**Issue by SpatzlHD** [iFraan/vandal.js#2]
If I understand correctly, this package uses an API from tracker.gg as data source! However, this API is not public and may not be used... This has something to do with Riot Games and the only API that Valorant Stats can expose is the Riot API itself, which requires an API key created by Riot. So in order not to get into legal trouble I would either change the data source to one authorized by Riot or stop this project.

**Comment by iFraan** [comment]
Adding a disclaimer.
