### ISSUE TITLE
API.raw() method not working

### ISSUE THREAD

**Issue by Reubzz** [iFraan/vandal.js#4]
TypeypeError: user.raw is not a function
    at E:\coding\Discord Bot\api\valorant.js:20:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by iFraan** [comment]
You are fetching the user previous to using the raw function, right?

**Comment by iFraan** [comment]
Nope, my bad. Should be fixed now, just update with npm.
